#ifndef SQDB_ERR_H_
#define SQDB_ERR_H_
#include <sqstd/sqfmterror.h>

//////////////////////////////////////////////////////////////////////////
//10000~10500	数据库错误，包括数据库系统本身的错误
SQMAPPING_ERROR_MESSAGE(DB_CONNECT_ERR, 10000, "数据库连接错误")
SQMAPPING_ERROR_MESSAGE(DB_QUERY_ERR, 10001, "数据库查询错误")
SQMAPPING_ERROR_MESSAGE(DB_OPER_ERR, 10002, "数据操作失败")
SQMAPPING_ERROR_MESSAGE(DB_ERR, 10003, "数据库异常")
SQMAPPING_ERROR_MESSAGE(DB_CONNECT_POOL_FULL_ERR, 10004, "数据库连接池错误")
SQMAPPING_ERROR_MESSAGE(DB_MEMEROY_ERR, 10005, "数据库操作内存错误")
SQMAPPING_ERROR_MESSAGE(DB_TABLE_NOT_FOUND, 10006, "找不到指定的数据库表")
SQMAPPING_ERROR_MESSAGE(DB_BAD_PARAM, 10007, "错误的数据库参数")
SQMAPPING_ERROR_MESSAGE(DB_NO_DATA, 10008, "找不到指定的数据")
SQMAPPING_ERROR_MESSAGE(DB_BAD_TRANSATION, 10009, "错误的事务嵌套")
SQMAPPING_ERROR_MESSAGE(DB_BAD_PRIMARY_KEY, 10010, "错误的主键")
SQMAPPING_ERROR_MESSAGE(DB_BAD_CONDITION, 10011, "错误的查询条件")
SQMAPPING_ERROR_MESSAGE(DB_BAD_UNIQUE_ID, 10012, "主键生成失败")
SQMAPPING_ERROR_MESSAGE(DB_NO_PROTO_MESSAGE, 10013, "找不到指定的通讯消息")
SQMAPPING_ERROR_MESSAGE(MEM_BAD_STATUS, 10014, "错误的内存状态")

#endif